ALTER TABLE tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE attribute_definitions DISABLE ROW LEVEL SECURITY;
ALTER TABLE quick_replies DISABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_flows DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
